//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _241613001_Mehmet_Kıvrak_NtpProje.pages // Kontrol edin!
{
    public partial class ekip : System.Web.UI.Page // Kontrol edin!
    {
        protected global::System.Web.UI.WebControls.Repeater rptEkip;
    }
}